---
title: Plasticine Caterpillar Practical
author: Thomas Holland (th675)
date: 1st November 2022
documentclass: article
classoption: a4paper
output:
  pdf_document:
      toc: true
      number_sections: true
bibliography: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#package import
library(tidyverse)
library(ggplot2)
library(readr)
```

# Introduction

# Data cleaning

```{r}
# "Character","Plant height (cm)",,,"Inflorescence height (mm)",,,"Pedicel Length (mm)",,,"Capitulum Length (mm)",,,"Capitulum Width (mm)",,,"Number of Ray Florets",,,"Length of Ray Florest (mm)",,,"Width of Ray Florets (mm)",,,"Longest leaf length (cm)",,,"Midleaf length (cm)",,,"Number of midleaf lobes",,,"Leaf dissection",,,"Standardized leaf perimeter",,,"Seed length (mm)",,,"Total number of seeds ",,,"Pollen pore size (uM)",,
# "Species","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv","Ss","Sc","Sv"
# "Individual 1",23.48,39.56,28.69,18.99,19.2,19.85,9.02,9.22,9.09,7.2,9.13,13.21,3.39,4.39,5.42,0,10.64,12.55,0,7.05,12.28,0,2.32,2.86,15.85,12.53,15.53,8.59,7.76,7.93,9.41,9.78,9.69,5.85,6,6.37,2.34,2.86,3.63,2.42,3.24,1.77,55.4,72.05,96.8,8.15,11.56,7.83
#  etc

#read in data
data <- read_csv("dataset.csv")

# for each of the individual rows, 1st, 4th, 7th etc is for species Ss, the 2nd, 5th, 8th etc is for Sc and the 3rd, 6th, 9th etc is for Sv

# for each of the characters, make a dataframe for each individual with a column for the species

df <- data.frame()

for (i in 1:ncol(data)){
  if (i %% 3 == 1){
    df <- rbind(df, data.frame(Species = "Ss", Character = colnames(data)[i], Value = data[,i]))
  } else if (i %% 3 == 2){
    df <- rbind(df, data.frame(Species = "Sc", Character = colnames(data)[i], Value = data[,i]))
  } else if (i %% 3 == 0){
    df <- rbind(df, data.frame(Species = "Sv", Character = colnames(data)[i], Value = data[,i]))
  }
}

print(head(df))
```